sfile = input("Enter a file to open: ")
dfile = input("Enter a file to open: ")
f1 = open(sfile,"r")
data = f1.read()
f2 = open(dfile,"w")
f2.write(data)
print("Data copied successfully")
f1.close()
f2.close()
