f = open("cse.txt","r")
data = f.read()
print(data)
print("Name of the file",f.name)
print("Mode of the file",f.mode)
print("File closed",f.closed)
print("File is readable",f.readable())
print("File is writable",f.writable())
f.close()
print("File Closed",f.closed)
