sfile = input("Enter a file to open: ")
dfile = input("Enter a file to open: ")
f1 = open(sfile,"r")
data = f1.read()
print(type(data))
f2 = open(dfile,"w")
f2.writelines(data)
print("Data Copied Successfully")
f1.close()
f2.close()
